services:
  mysql:
    image: "uniuu/zotprime-db:${VER}"
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQLROOTPASSWORD}
      - MARIADB_DATABASE=${MYSQLDATABASE}
      - MARIADB_USER=${MYSQLUSER}
      - MARIADB_PASSWORD=${MYSQLPASSWORD}
    volumes:
      - dbdata2:/run/mysqld
      - dbdata:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      zotprime:
        ipv4_address: 10.5.5.2
  elasticsearch:
    image: "uniuu/zotprime-elasticsearch:${VER}"
    mem_limit: 1024m
    mem_reservation: 1024m
    environment:
      - cluster.name=zotero
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false 
      - discovery.type=single-node
      - logger.level=WARN
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      zotprime:
        ipv4_address: 10.5.5.3
  redis:
    image: "uniuu/zotprime-redis:${VER}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      zotprime:
        ipv4_address: 10.5.5.4
  memcached:
    image: "uniuu/zotprime-memcached:${VER}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      zotprime:
        ipv4_address: 10.5.5.5
  localstack:
    image: "uniuu/zotprime-localstack:${VER}"
    environment:
      - SERVICES=sns,sqs,apigateway
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      zotprime:
        ipv4_address: 10.5.5.6
  minio:
    image: "uniuu/zotprime-minio:${VER}"
    environment:
      - MINIO_ROOT_USER=${MINIOROOTUSER}
      - MINIO_ROOT_PASSWORD=${MINIOROOTPASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      zotprime:
        ipv4_address: 10.5.5.7
  zotprime-dataserver:
    image: "uniuu/zotprime-dataserver:${VER}"
    ports:
      - "8080:80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - RUN_USER=apache
      - RUN_GROUP=apache
      - DSURI=${DSHOST}
      - S3POINTURI=${S3HOST}
    depends_on:
      - mysql
      - elasticsearch
      - redis
      - memcached
      - tinymceclean
      - streamserver
    restart: always
    networks:
      zotprime:
        aliases:
          - dataserver
        ipv4_address: 10.5.5.8
  tinymceclean:
    image: "uniuu/zotprime-tinymceclean:${VER}"
    depends_on:
      - mysql
      - elasticsearch
      - redis
      - memcached
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      zotprime:
        ipv4_address: 10.5.5.9
  streamserver:
    image: "uniuu/zotprime-streamserver:${VER}"
    ports:
      - "8081:81"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - mysql
      - elasticsearch
      - redis
      - memcached
    networks:
      zotprime:
        ipv4_address: 10.5.5.10
  zotprime-phpmyadmin:
    image: "uniuu/zotprime-phpmyadmin:${VER}"
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      zotprime:
        ipv4_address: 10.5.5.11
volumes:
  dbdata2:
   driver: local
  dbdata:
   driver: local
networks:
  zotprime:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.5.0/28
          gateway: 10.5.5.1